/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kontenmart;

import inc.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.table.TableModel;

/**
 *
 * @author Aang
 */
public class databarang extends javax.swing.JInternalFrame {
      Connection con=config.conn();
    Statement st;
    ResultSet rs;
    String makanan, minuman;
    private void tampil(){
        
        DefaultTableModel modell= new DefaultTableModel();
            modell.addColumn("No");
            modell.addColumn("ID");
            modell.addColumn("Nama");
            modell.addColumn("Jenis Barang");
            modell.addColumn("Harga Beli");
            modell.addColumn("Harga Jual");
            modell.addColumn("Jumlah Barang");
            modell.addColumn("Tanggal Masuk");
            modell.addColumn("ID Perusahaan");
        try{
            String sql = "SELECT * FROM barang";
            st=con.createStatement();
            rs=st.executeQuery(sql);
            
            int no =0;
            while(rs.next()){
                no++;
                modell.addRow(new Object[]{
                   no, rs.getString("id_barang"), rs.getString("nama_barang"),rs.getString("jenis_barang"),
                    rs.getString("harga_beli"),rs.getString("harga_jual"),rs.getString("stok")
                    ,rs.getDate("tanggal_masuk"), rs.getString("id_perusahaan")
                });
            }
            tabel.setModel(modell);
        }catch(Exception e){
            System.out.println(e.getLocalizedMessage());
        }
    }
    
    private void reset(){
        id.setText("");
        namabrg.setText("");
         
        hargabeli.setText("");
        hargajual.setText("");
        stok.setText("");
        tanggal.setText("");
        id_perusahaan.setText("");
        
        
    }
    
    
    /**
     * Creates new form databarang
     */
    public databarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        namabrg = new javax.swing.JTextField();
        hargabeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pen = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hargajual = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id_perusahaan = new javax.swing.JTextField();
        jenisbarang = new javax.swing.JComboBox();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("DATA BARANG");

        jLabel2.setText("ID");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Jenis Barang");

        jLabel5.setText("Harga Beli");

        hargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabeliActionPerformed(evt);
            }
        });

        jLabel7.setText("Pencarian");

        pen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penActionPerformed(evt);
            }
        });
        pen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                penKeyPressed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga Jual");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Nama", "Jenis Makanan", "Harga Beli", "Harga Jual", "Jumlah Barang", "Tanggal Masuk", "ID Perusahaan"
            }
        ));
        tabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tabelMouseDragged(evt);
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabel8.setText("Jumlah Barang");

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        jLabel9.setText("Tanggal Masuk");

        jLabel10.setText("ID Prusahaan");

        jenisbarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "makanan", "minuman", "kosmetik" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hargabeli, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(namabrg, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(hargajual)
                                    .addComponent(stok)
                                    .addComponent(tanggal)
                                    .addComponent(id_perusahaan)
                                    .addComponent(jenisbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(simpan)
                                    .addComponent(hapus))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reset)
                                    .addComponent(ubah))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(92, 92, 92)
                                .addComponent(pen, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namabrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(id_perusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubah)
                    .addComponent(simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(reset))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabeliActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String jenis = jenisbarang.getSelectedItem().toString();
        
        try{
            String sql ="INSERT INTO barang VALUES('"+id.getText()+"', '" +namabrg.getText()+"', '"+jenis+"', "+
                    hargabeli.getText()+", "+hargajual.getText()+", "+stok.getText()+", now(), '"+id_perusahaan.getText()+"')";
            st = con.createStatement();
            st.executeUpdate(sql);
            reset();
            tampil();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
    reset();        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
         try{
            String sql ="DELETE FROM barang WHERE id_barang = '"+id.getText()+"'";
            st = con.createStatement();
            st.executeUpdate(sql);
            reset();
            tampil();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        String jenis = jenisbarang.getSelectedItem().toString();  
        
        try{
            String sql ="UPDATE barang SET nama_barang= '"+namabrg.getText()+
                    "', jenis_barang= '"+jenis+"', harga_beli = "+hargabeli.getText()+
                    ", harga_jual= "+hargajual.getText()+", stok= "+stok.getText()+
                    ", tanggal_masuk= now()"+
                    ", id_perusahaan= '"+id_perusahaan.getText()+"' WHERE id_barang = '"+id.getText()+"'";// mencari beradsarkan id yang terpilih
                    // kalo gk pake where semua akan terupdate
            st = con.createStatement();
            st.executeUpdate(sql);
            reset();
            tampil();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void penActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_penActionPerformed

    private void penKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_penKeyPressed
        
        DefaultTableModel modell= new DefaultTableModel();
            modell.addColumn("No");
            modell.addColumn("ID");
            modell.addColumn("Nama");
            modell.addColumn("Jenis Barang");
            modell.addColumn("Harga Beli");
            modell.addColumn("Harga Jual");
            modell.addColumn("Jumlah Barang");
            modell.addColumn("Tanggal Masuk");
            modell.addColumn("ID Perusahaan");
        try{
            String sql = "SELECT * FROM barang WHERE id_barang LIKE '%"+pen.getText()+"%' or nama_barang LIKE '%"+pen.getText()+"%' or harga_beli LIKE '%"+pen.getText()+"%' or harga_jual LIKE '%"+
                  pen.getText()+ "%'";
            st=con.createStatement();
            rs=st.executeQuery(sql);
            
            int no =0;
            while(rs.next()){
                no++;
                modell.addRow(new Object[]{
                   no, rs.getString("id_barang"), rs.getString("nama_barang"),rs.getString("jenis_barang"),
                    rs.getString("harga_beli"),rs.getString("harga_jual"),rs.getString("stok"),
                    rs.getString("tanggal_masuk"),rs.getString("id_perusahaan")
                });
            }
            tabel.setModel(modell);
        }catch(Exception e){
            System.out.println(e.getLocalizedMessage());
        }
        
    
        // TODO add your handling code here:
    }//GEN-LAST:event_penKeyPressed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
tampil();        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void tabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseDragged
         
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseDragged

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
      
        int baris = tabel.getSelectedRow();
        TableModel model = tabel.getModel();
        
        
        id.setText(tabel.getModel().getValueAt(baris, 1).toString()); 
        namabrg.setText(tabel.getModel().getValueAt(baris, 2).toString());
        String jenis = model.getValueAt(baris, 3).toString();
            switch(jenis){
                case "makanan":
                    jenisbarang.setSelectedIndex(0);
                    break;
                    
                case "minuman":
                    jenisbarang.setSelectedIndex(1);
                    break;
                    
                case "kosmetik":
                    jenisbarang.setSelectedIndex(2);
                    break;
            }
        hargabeli.setText(tabel.getModel().getValueAt(baris, 4).toString()); 
        hargajual.setText(tabel.getModel().getValueAt(baris, 5).toString());
        stok.setText(tabel.getModel().getValueAt(baris, 6).toString());
        tanggal.setText(tabel.getModel().getValueAt(baris, 7).toString());
        id_perusahaan.setText(tabel.getModel().getValueAt(baris, 8).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField hargajual;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_perusahaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jenisbarang;
    private javax.swing.JTextField namabrg;
    private javax.swing.JTextField pen;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
